version: '3.8'

services:
  # 前端 + Nginx
  nginx:
    build: ./frontend
    container_name: nursing-nginx
    ports:
      - "80:80"
    networks:
      - nursing-network
    depends_on:
      - backend

  # 后端 - Spring Boot
  backend:
    build: ./backend
    container_name: nursing-backend
    ports:
      - "8081:8081"
    networks:
      - nursing-network
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/nursing_home?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

networks:
  nursing-network:
    driver: bridge
    external: true
