jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://119.91.226.203:3306/nursing_home?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
jdbc.username=root
jdbc.password=1234
